[FE] [MERGE] add rating page & display all comments VisitorWeb
GuardosEpitech/Guardos pull request #78
Opened 2024-03-21 20:24 UTC by Alban-de-tourtier

### 🛠 Changes being made

Add the review page and display all the review of the restaurant under the rating form

### 🧪 Test plan

You can test the feature using the "Add a review" button and fill the form and check behind to see it 

### 🏎 PR checklist

1. Read the ticket
- [X] Read the related ticket on Jira and understand the requirements for this ticket. In case anything is unclear, ask the ticket creator or ticket executor.
2. Matching PR description
- [X] Check that the PR description on GitHub is aligned with the ticket description on Jira.
3. Review the changes on GitHub
- [X] is the current version of the destination branch (mostly main) merged into the PR branch?
- [X] does it fulfill the definition of done for the ticket?
- [X] were the tests adjusted or extended for the changed behavior?
- [X] was the documentation adjusted or extended for changed behavior?
- [X] does it align with the team code guidelines?
- [X] check readability of code - is it easy to understand what is happening in the code snippets?
- [X] proper naming
- [X] is it logical?
- [X] are there any performance issues?
- [X] could it be improved / simplified?
4. Execute locally / in testing environment
- [X] Execute the code locally and check if there are any issues. Test whether the new behavior from the ticket acts as expected. Try to think of edge cases and test them.
5. Run tests
- [X] Run the tests locally and check that all of them succeed.
6. Linting & Formatting
- [X] Check that the changes didn’t cause any linting or formatting warnings of errors.
7. Submit Feedback
- [X] Approve if all of the following points fulfilled:
   - all previous steps did not reveal any issues
   - there are no open comments on the PR

- [X] otherwise, request changes with specific comments (constructive) on what to change!

2024-03-22 02:30 UTC, JosefineM2000 requested changes

2024-03-22 02:30 UTC, JosefineM2000 commented on packages/visitorWeb/.env
> +DB_HOST="http://localhost:"
please remove this change, localhost can only be used for local development, not on the server.

2024-03-22 02:30 UTC, JosefineM2000 commented on packages/visitorWeb/src/services/ratingCalls.ts
> +        console.log(response.data);
please remove log

2024-03-22 02:30 UTC, JosefineM2000 commented on packages/visitorWeb/src/services/ratingCalls.ts
> +    console.log(comment, note),
please remove log

2024-03-22 02:30 UTC, JosefineM2000 commented on packages/visitorWeb/src/services/ratingCalls.ts
> +        console.log(response.data);
please remove log

2024-03-22 02:30 UTC, JosefineM2000 commented on packages/visitorWeb/src/components/RestoCard/RestoCard.tsx
> +            <Rating restoRating={rating} restoRatingsCount={ratingCount} restoName={name} />
restoRating should display the number and correct average rating in restocard as well, not just on review page

2024-03-22 02:30 UTC, JosefineM2000 commented on packages/visitorWeb/src/pages/RatingPage/RatingPage.tsx
> +  const addReview = () => {
please add success and failure popups so the user knows if submission was a success

2024-03-22 02:30 UTC, JosefineM2000 commented on packages/visitorWeb/src/pages/RatingPage/RatingPage.tsx
Please write tests for your new component

2024-03-25 12:03 UTC, Alban-de-tourtier commented on packages/visitorWeb/.env
> +DB_HOST="http://localhost:"
yes I will but its for this reason that the .env is always in the .gitignore

2024-03-26 00:51 UTC, JosefineM2000 requested changes

2024-03-26 00:51 UTC, JosefineM2000 commented on packages/visitorWeb/src/components/RestoCard/Rating/Rating.tsx
> +      <span className={styles.AverageTxt}>{averageRating()}</span>
instead of the average, this should display the number of submitted ratings.

2024-03-26 00:51 UTC, JosefineM2000 commented on packages/restoWeb/src/components/RestoCard/RestoCard.tsx
> +            <RatingDisplay
please also update the ratingDisplay in restoWeb, not just visitorWeb to display the correct data (avg rating and number of ratings)

2024-03-26 00:56 UTC, JosefineM2000 requested changes

2024-03-26 00:56 UTC, JosefineM2000 commented on packages/visitorWeb/cypress/e2e/RatingPageTest/RatingPageTest.cy.ts
> +describe('Access to the Rating page', () => {
test is not passing:  CypressError: `cy.click()` can only be called on a single element. Your subject contained 26 elements. Pass `{ multiple: true }` if you want to serially click each element.

2024-03-26 01:38 UTC, JosefineM2000 approved these changes

2024-03-26 01:47 UTC, merged