[MERGE] [FE] Merge CreateRestoQR -> Main
GuardosEpitech/Guardos pull request #94
Opened 2024-04-22 21:07 UTC by Alban-de-tourtier

### 🛠 Changes being made

I added QRcode call on the BE and I added a button on the restoWeb and modify visitor menu URL

### ✨ What's the context?

PLD

### 🧪 Test plan

All good

### 🏎 PR checklist

1. Read the ticket
- [x] Read the related ticket on Jira and understand the requirements for this ticket. In case anything is unclear, ask the ticket creator or ticket executor.
2. Matching PR description
- [x] Check that the PR description on GitHub is aligned with the ticket description on Jira.
3. Review the changes on GitHub
- [x] is the current version of the destination branch (mostly main) merged into the PR branch?
- [x] does it fulfill the definition of done for the ticket?
- [x] were the tests adjusted or extended for the changed behavior?
- [x] was the documentation adjusted or extended for changed behavior?
- [x] does it align with the team code guidelines?
- [x] check readability of code - is it easy to understand what is happening in the code snippets?
- [x] proper naming
- [x] is it logical?
- [x] are there any performance issues?
- [x] could it be improved / simplified?
4. Execute locally / in testing environment
- [x] Execute the code locally and check if there are any issues. Test whether the new behavior from the ticket acts as expected. Try to think of edge cases and test them.
5. Run tests
- [x] Run the tests locally and check that all of them succeed.
6. Linting & Formatting
- [x] Check that the changes didn’t cause any linting or formatting warnings of errors.
7. Submit Feedback
- [x] Approve if all of the following points fulfilled:
   - all previous steps did not reveal any issues
   - there are no open comments on the PR

- [x] otherwise, request changes with specific comments (constructive) on what to change!

2024-04-23 04:44 UTC, RenanDbs approved these changes

2024-04-24 07:37 UTC, JosefineM2000 requested changes

2024-04-24 07:37 UTC, JosefineM2000 commented on packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
> +          Get my Menu QRCODE
Please use i18n here

2024-05-29 03:44 UTC, JosefineM2000 approved these changes

2024-11-16 12:09 UTC, closed without merging